name: sendingnetworkdart_api_lite
description: Dead simple data model for the sdn.org client-server API.
version: 0.1.0
homepage: https://github.com/Sending-Network
repository: https://github.com/Sending-Network/sendingnetworkdart_api_lite
issues: https://github.com/Sending-Network/sendingnetwork-dart/tree/main/sendingnetworkdart_api_lite

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  enhanced_enum: ^0.2.4
  http: ^1.1.0
  mime: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.8
  enhanced_enum_generator: ^0.2.4
  import_sorter: ^4.6.0
  lints: ^2.0.0
  test: ^1.14.4
 
dependency_overrides:
# uncomment for local development
#  sdn:
#    path: '../famedlysdk'
